/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Disease = IDL.Record({
  'name' : IDL.Text,
  'treatmentAdvice' : IDL.Text,
  'symptoms' : IDL.Vec(IDL.Text),
  'severity' : IDL.Text,
  'affectedSpecies' : IDL.Vec(IDL.Text),
});
export const SymptomCheckResult = IDL.Record({
  'potentialDiseases' : IDL.Vec(Disease),
  'matchedSymptoms' : IDL.Vec(IDL.Text),
});
export const Animal = IDL.Record({
  'age' : IDL.Nat,
  'symptoms' : IDL.Vec(IDL.Text),
  'breed' : IDL.Text,
  'species' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAnimal' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'addDisease' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
      [],
      [],
    ),
  'checkSymptoms' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text)],
      [SymptomCheckResult],
      ['query'],
    ),
  'getAnimal' : IDL.Func([IDL.Nat], [Animal], ['query']),
  'getDisease' : IDL.Func([IDL.Text], [Disease], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Disease = IDL.Record({
    'name' : IDL.Text,
    'treatmentAdvice' : IDL.Text,
    'symptoms' : IDL.Vec(IDL.Text),
    'severity' : IDL.Text,
    'affectedSpecies' : IDL.Vec(IDL.Text),
  });
  const SymptomCheckResult = IDL.Record({
    'potentialDiseases' : IDL.Vec(Disease),
    'matchedSymptoms' : IDL.Vec(IDL.Text),
  });
  const Animal = IDL.Record({
    'age' : IDL.Nat,
    'symptoms' : IDL.Vec(IDL.Text),
    'breed' : IDL.Text,
    'species' : IDL.Text,
  });
  
  return IDL.Service({
    'addAnimal' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'addDisease' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
        [],
        [],
      ),
    'checkSymptoms' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [SymptomCheckResult],
        ['query'],
      ),
    'getAnimal' : IDL.Func([IDL.Nat], [Animal], ['query']),
    'getDisease' : IDL.Func([IDL.Text], [Disease], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };