/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Animal {
  'age' : bigint,
  'symptoms' : Array<string>,
  'breed' : string,
  'species' : string,
}
export interface Disease {
  'name' : string,
  'treatmentAdvice' : string,
  'symptoms' : Array<string>,
  'severity' : string,
  'affectedSpecies' : Array<string>,
}
export interface SymptomCheckResult {
  'potentialDiseases' : Array<Disease>,
  'matchedSymptoms' : Array<string>,
}
export interface _SERVICE {
  'addAnimal' : ActorMethod<
    [bigint, string, string, bigint, Array<string>],
    undefined
  >,
  'addDisease' : ActorMethod<
    [string, Array<string>, Array<string>, string, string],
    undefined
  >,
  'checkSymptoms' : ActorMethod<[string, Array<string>], SymptomCheckResult>,
  'getAnimal' : ActorMethod<[bigint], Animal>,
  'getDisease' : ActorMethod<[string], Disease>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];